[project]
name = 'Snabbgenomspelning'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.onchain-notepad]
path = 'contracts/onchain-notepad.clar'
clarity_version = 4
epoch = 'latest'

[contracts.personal-counter]
path = 'contracts/personal-counter.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-wallet-registry]
path = 'contracts/simple-wallet-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.status-logger]
path = 'contracts/status-logger.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
