[project]
name = 'Snabbgenomspelning'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.aboki-escrow-lite]
path = 'contracts/aboki-escrow-lite.clar'
clarity_version = 4
epoch = 'latest'

[contracts.christmas-red-envelope]
path = 'contracts/christmas-red-envelope.clar'
clarity_version = 4
epoch = 'latest'

[contracts.daily-checkin]
path = 'contracts/daily-checkin.clar'
clarity_version = 4
epoch = 'latest'

[contracts.feedback-box]
path = 'contracts/feedback-box.clar'
clarity_version = 4
epoch = 'latest'

[contracts.onchain-notepad]
path = 'contracts/onchain-notepad.clar'
clarity_version = 4
epoch = 'latest'

[contracts.personal-counter]
path = 'contracts/personal-counter.clar'
clarity_version = 4
epoch = 'latest'

[contracts.prediction-market-lite]
path = 'contracts/prediction-market-lite.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-points]
path = 'contracts/simple-points.clar'
clarity_version = 4
epoch = 'latest'

[contracts.simple-wallet-registry]
path = 'contracts/simple-wallet-registry.clar'
clarity_version = 4
epoch = 'latest'

[contracts.status-logger]
path = 'contracts/status-logger.clar'
clarity_version = 4
epoch = 'latest'
[repl.analysis]
passes = [
    'call_checker',
    'check_checker',
]

[repl.analysis.lints]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
